{
    'name': 'Dashboard Studio',
    'summary': 'Dashboard Studio - Dashboard Designer - Dashboard Ninja - Dashboard Builder. Build Dashboard View on the fly without any technical knowledge. dashboard builder, dashboard ninja, dashboard designer, dashboard studio, odoo studio',
    'version': '1.0',
    'category': 'Web',
    'description': """
        Dashboard Studio - Dashboard Designer - Dashboard Ninja - Dashboard Builder. Build Dashboard View on the fly without any technical knowledge. dashboard builder, dashboard ninja, dashboard designer, dashboard studio, odoo studio
    """,
    'author': "apps.odoo.community@gmail.com",
    'depends': ['web', 'mail'],
    'data': [
        # 'views/templates.xml',
        # 'views/ir_ui_menu_view.xml',
        'security/view_dynamic_security.xml',
        'security/ir.model.access.csv',
    ],
    'qweb': [
        # 'static/src/xml/views.xml',
        # 'static/src/xml/widgets.xml',
        # 'static/src/xml/base.xml',
        # 'static/src/xml/fields.xml',
        # 'static/src/xml/gantt_view.xml',
        # 'static/src/xml/planning_view.xml',
        # 'static/src/xml/kanban_view.xml',
        # 'static/src/xml/dashboard_view.xml',
    ],
    'assets': {
        'web.assets_qweb': [
            '/dashboard_studio/static/src/xml/views.xml',
            '/dashboard_studio/static/src/xml/widgets.xml',
            '/dashboard_studio/static/src/xml/base.xml',
            '/dashboard_studio/static/src/xml/fields.xml',
            # '/dashboard_studio/static/src/xml/gantt_view.xml',
            '/dashboard_studio/static/src/xml/planning_view.xml',
            '/dashboard_studio/static/src/xml/kanban_view.xml',
            '/dashboard_studio/static/src/xml/dashboard_view.xml',
            '/dashboard_studio/static/src/js/navbar/dashboard_menu.xml',
            # '/dashboard_studio/static/src/js/navbar/navbar.xml',
            '/dashboard_studio/static/src/js/navbar/menu_creator.xml',
        ],
        'web.assets_backend': [
            '/dashboard_studio/static/src/scss/views.scss',
            '/dashboard_studio/static/src/scss/base.scss',
            '/dashboard_studio/static/src/scss/fields.scss',
            '/dashboard_studio/static/src/scss/widgets.scss',
            '/dashboard_studio/static/src/scss/planning_view.scss',
            # '/dashboard_studio/static/src/scss/gantt_view.scss',
            '/dashboard_studio/static/src/scss/dashboard_view.scss',
            # '/dashboard_studio/static/src/scss/test.scss',

            '/dashboard_studio/static/src/js/navbar/navbar.scss',
            '/dashboard_studio/static/src/js/navbar/dashboard_menu.scss',
            '/dashboard_studio/static/src/js/navbar/navbar.js',
            '/dashboard_studio/static/src/js/navbar/dashboard_menu.js',
            '/dashboard_studio/static/src/js/navbar/menu_creator.js',
            '/dashboard_studio/static/src/js/dashboard_edit/active_dashboard.js',

            '/dashboard_studio/static/src/js/base.js',
            '/dashboard_studio/static/src/js/views_edit_base.js',
            '/dashboard_studio/static/src/js/base_center.js',
            '/dashboard_studio/static/src/js/dashboards_center.js',
            '/dashboard_studio/static/src/js/views_center.js',
            '/dashboard_studio/static/src/js/abstract_controller.js',
            '/dashboard_studio/static/src/js/fields/basic_fields.js',
            '/dashboard_studio/static/src/js/widgets/basic_widgets.js',
            '/dashboard_studio/static/src/js/views/planning_view/planning_controller.js',
            '/dashboard_studio/static/src/js/views/planning_view/planning_model.js',
            '/dashboard_studio/static/src/js/views/planning_view/planning_renderer.js',
            '/dashboard_studio/static/src/js/views/planning_view/planning_view.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_controller.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_model.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_renderer.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_view.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_card.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_modify.js',
            '/dashboard_studio/static/src/js/views/dashboard_view/dashboard_widget.js',
            '/dashboard_studio/static/src/js/views/graph_view/graph_renderer.js',
            '/dashboard_studio/static/src/js/views/graph_view/graph_view.js',
            '/dashboard_studio/static/src/js/dashboard_edit/chart.js',
            '/dashboard_studio/static/src/js/views_edit/calendar.js',
            '/dashboard_studio/static/src/js/views_edit/pivot.js',
            '/dashboard_studio/static/src/js/views_edit/activity.js',
            '/dashboard_studio/static/src/js/views_edit/kanban.js',
            '/dashboard_studio/static/src/js/views_edit/planning.js',
            '/dashboard_studio/static/src/js/views_edit/tree.js',
            '/dashboard_studio/static/src/js/dashboard_edit/dashboard_widgets.js',
            '/dashboard_studio/static/src/js/viewContainer.js',
        ],

    },
    'images': ['images/main_screen.jpg'],
    'price': 250,
    'currency': 'EUR',
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
    'images': [
        'static/description/module_image.jpg',
    ],
}
